/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShareRouteImport } from './routes/share'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as InspirationRouteImport } from './routes/inspiration'
import { Route as IndexRouteImport } from './routes/index'
import { Route as YarnIndexRouteImport } from './routes/yarn.index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProfilesIndexRouteImport } from './routes/profiles.index'
import { Route as PatternsIndexRouteImport } from './routes/patterns.index'
import { Route as NeedlesIndexRouteImport } from './routes/needles.index'
import { Route as GaugeIndexRouteImport } from './routes/gauge.index'
import { Route as ChartsIndexRouteImport } from './routes/charts.index'
import { Route as YarnNewRouteImport } from './routes/yarn.new'
import { Route as YarnCalcRouteImport } from './routes/yarn.calc'
import { Route as ProjectsNewRouteImport } from './routes/projects.new'
import { Route as ProfilesNewRouteImport } from './routes/profiles.new'
import { Route as PatternsNewRouteImport } from './routes/patterns.new'
import { Route as PatternsPatternIdRouteImport } from './routes/patterns.$patternId'
import { Route as GaugeNewRouteImport } from './routes/gauge.new'
import { Route as GaugeCalcRouteImport } from './routes/gauge.calc'
import { Route as ChartsNewRouteImport } from './routes/charts.new'
import { Route as ChartsChartIdRouteImport } from './routes/charts.$chartId'
import { Route as YarnYarnIdIndexRouteImport } from './routes/yarn.$yarnId.index'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects.$projectId.index'
import { Route as YarnYarnIdEditRouteImport } from './routes/yarn.$yarnId.edit'
import { Route as ProjectsProjectIdRefsRouteImport } from './routes/projects.$projectId.refs'
import { Route as ProjectsProjectIdLogRouteImport } from './routes/projects.$projectId.log'
import { Route as ProjectsProjectIdKnitRouteImport } from './routes/projects.$projectId.knit'
import { Route as ProjectsProjectIdEditRouteImport } from './routes/projects.$projectId.edit'
import { Route as ProfilesProfileIdEditRouteImport } from './routes/profiles.$profileId.edit'
import { Route as GaugeGaugeIdEditRouteImport } from './routes/gauge.$gaugeId.edit'

const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const InspirationRoute = InspirationRouteImport.update({
  id: '/inspiration',
  path: '/inspiration',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const YarnIndexRoute = YarnIndexRouteImport.update({
  id: '/yarn/',
  path: '/yarn/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesIndexRoute = ProfilesIndexRouteImport.update({
  id: '/profiles/',
  path: '/profiles/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternsIndexRoute = PatternsIndexRouteImport.update({
  id: '/patterns/',
  path: '/patterns/',
  getParentRoute: () => rootRouteImport,
} as any)
const NeedlesIndexRoute = NeedlesIndexRouteImport.update({
  id: '/needles/',
  path: '/needles/',
  getParentRoute: () => rootRouteImport,
} as any)
const GaugeIndexRoute = GaugeIndexRouteImport.update({
  id: '/gauge/',
  path: '/gauge/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartsIndexRoute = ChartsIndexRouteImport.update({
  id: '/charts/',
  path: '/charts/',
  getParentRoute: () => rootRouteImport,
} as any)
const YarnNewRoute = YarnNewRouteImport.update({
  id: '/yarn/new',
  path: '/yarn/new',
  getParentRoute: () => rootRouteImport,
} as any)
const YarnCalcRoute = YarnCalcRouteImport.update({
  id: '/yarn/calc',
  path: '/yarn/calc',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesNewRoute = ProfilesNewRouteImport.update({
  id: '/profiles/new',
  path: '/profiles/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternsNewRoute = PatternsNewRouteImport.update({
  id: '/patterns/new',
  path: '/patterns/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternsPatternIdRoute = PatternsPatternIdRouteImport.update({
  id: '/patterns/$patternId',
  path: '/patterns/$patternId',
  getParentRoute: () => rootRouteImport,
} as any)
const GaugeNewRoute = GaugeNewRouteImport.update({
  id: '/gauge/new',
  path: '/gauge/new',
  getParentRoute: () => rootRouteImport,
} as any)
const GaugeCalcRoute = GaugeCalcRouteImport.update({
  id: '/gauge/calc',
  path: '/gauge/calc',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartsNewRoute = ChartsNewRouteImport.update({
  id: '/charts/new',
  path: '/charts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartsChartIdRoute = ChartsChartIdRouteImport.update({
  id: '/charts/$chartId',
  path: '/charts/$chartId',
  getParentRoute: () => rootRouteImport,
} as any)
const YarnYarnIdIndexRoute = YarnYarnIdIndexRouteImport.update({
  id: '/yarn/$yarnId/',
  path: '/yarn/$yarnId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/projects/$projectId/',
  path: '/projects/$projectId/',
  getParentRoute: () => rootRouteImport,
} as any)
const YarnYarnIdEditRoute = YarnYarnIdEditRouteImport.update({
  id: '/yarn/$yarnId/edit',
  path: '/yarn/$yarnId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRefsRoute = ProjectsProjectIdRefsRouteImport.update({
  id: '/projects/$projectId/refs',
  path: '/projects/$projectId/refs',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdLogRoute = ProjectsProjectIdLogRouteImport.update({
  id: '/projects/$projectId/log',
  path: '/projects/$projectId/log',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdKnitRoute = ProjectsProjectIdKnitRouteImport.update({
  id: '/projects/$projectId/knit',
  path: '/projects/$projectId/knit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdEditRoute = ProjectsProjectIdEditRouteImport.update({
  id: '/projects/$projectId/edit',
  path: '/projects/$projectId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesProfileIdEditRoute = ProfilesProfileIdEditRouteImport.update({
  id: '/profiles/$profileId/edit',
  path: '/profiles/$profileId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const GaugeGaugeIdEditRoute = GaugeGaugeIdEditRouteImport.update({
  id: '/gauge/$gaugeId/edit',
  path: '/gauge/$gaugeId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inspiration': typeof InspirationRoute
  '/settings': typeof SettingsRoute
  '/share': typeof ShareRoute
  '/charts/$chartId': typeof ChartsChartIdRoute
  '/charts/new': typeof ChartsNewRoute
  '/gauge/calc': typeof GaugeCalcRoute
  '/gauge/new': typeof GaugeNewRoute
  '/patterns/$patternId': typeof PatternsPatternIdRoute
  '/patterns/new': typeof PatternsNewRoute
  '/profiles/new': typeof ProfilesNewRoute
  '/projects/new': typeof ProjectsNewRoute
  '/yarn/calc': typeof YarnCalcRoute
  '/yarn/new': typeof YarnNewRoute
  '/charts/': typeof ChartsIndexRoute
  '/gauge/': typeof GaugeIndexRoute
  '/needles/': typeof NeedlesIndexRoute
  '/patterns/': typeof PatternsIndexRoute
  '/profiles/': typeof ProfilesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/yarn/': typeof YarnIndexRoute
  '/gauge/$gaugeId/edit': typeof GaugeGaugeIdEditRoute
  '/profiles/$profileId/edit': typeof ProfilesProfileIdEditRoute
  '/projects/$projectId/edit': typeof ProjectsProjectIdEditRoute
  '/projects/$projectId/knit': typeof ProjectsProjectIdKnitRoute
  '/projects/$projectId/log': typeof ProjectsProjectIdLogRoute
  '/projects/$projectId/refs': typeof ProjectsProjectIdRefsRoute
  '/yarn/$yarnId/edit': typeof YarnYarnIdEditRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/yarn/$yarnId/': typeof YarnYarnIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inspiration': typeof InspirationRoute
  '/settings': typeof SettingsRoute
  '/share': typeof ShareRoute
  '/charts/$chartId': typeof ChartsChartIdRoute
  '/charts/new': typeof ChartsNewRoute
  '/gauge/calc': typeof GaugeCalcRoute
  '/gauge/new': typeof GaugeNewRoute
  '/patterns/$patternId': typeof PatternsPatternIdRoute
  '/patterns/new': typeof PatternsNewRoute
  '/profiles/new': typeof ProfilesNewRoute
  '/projects/new': typeof ProjectsNewRoute
  '/yarn/calc': typeof YarnCalcRoute
  '/yarn/new': typeof YarnNewRoute
  '/charts': typeof ChartsIndexRoute
  '/gauge': typeof GaugeIndexRoute
  '/needles': typeof NeedlesIndexRoute
  '/patterns': typeof PatternsIndexRoute
  '/profiles': typeof ProfilesIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/yarn': typeof YarnIndexRoute
  '/gauge/$gaugeId/edit': typeof GaugeGaugeIdEditRoute
  '/profiles/$profileId/edit': typeof ProfilesProfileIdEditRoute
  '/projects/$projectId/edit': typeof ProjectsProjectIdEditRoute
  '/projects/$projectId/knit': typeof ProjectsProjectIdKnitRoute
  '/projects/$projectId/log': typeof ProjectsProjectIdLogRoute
  '/projects/$projectId/refs': typeof ProjectsProjectIdRefsRoute
  '/yarn/$yarnId/edit': typeof YarnYarnIdEditRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
  '/yarn/$yarnId': typeof YarnYarnIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/inspiration': typeof InspirationRoute
  '/settings': typeof SettingsRoute
  '/share': typeof ShareRoute
  '/charts/$chartId': typeof ChartsChartIdRoute
  '/charts/new': typeof ChartsNewRoute
  '/gauge/calc': typeof GaugeCalcRoute
  '/gauge/new': typeof GaugeNewRoute
  '/patterns/$patternId': typeof PatternsPatternIdRoute
  '/patterns/new': typeof PatternsNewRoute
  '/profiles/new': typeof ProfilesNewRoute
  '/projects/new': typeof ProjectsNewRoute
  '/yarn/calc': typeof YarnCalcRoute
  '/yarn/new': typeof YarnNewRoute
  '/charts/': typeof ChartsIndexRoute
  '/gauge/': typeof GaugeIndexRoute
  '/needles/': typeof NeedlesIndexRoute
  '/patterns/': typeof PatternsIndexRoute
  '/profiles/': typeof ProfilesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/yarn/': typeof YarnIndexRoute
  '/gauge/$gaugeId/edit': typeof GaugeGaugeIdEditRoute
  '/profiles/$profileId/edit': typeof ProfilesProfileIdEditRoute
  '/projects/$projectId/edit': typeof ProjectsProjectIdEditRoute
  '/projects/$projectId/knit': typeof ProjectsProjectIdKnitRoute
  '/projects/$projectId/log': typeof ProjectsProjectIdLogRoute
  '/projects/$projectId/refs': typeof ProjectsProjectIdRefsRoute
  '/yarn/$yarnId/edit': typeof YarnYarnIdEditRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/yarn/$yarnId/': typeof YarnYarnIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/inspiration'
    | '/settings'
    | '/share'
    | '/charts/$chartId'
    | '/charts/new'
    | '/gauge/calc'
    | '/gauge/new'
    | '/patterns/$patternId'
    | '/patterns/new'
    | '/profiles/new'
    | '/projects/new'
    | '/yarn/calc'
    | '/yarn/new'
    | '/charts/'
    | '/gauge/'
    | '/needles/'
    | '/patterns/'
    | '/profiles/'
    | '/projects/'
    | '/yarn/'
    | '/gauge/$gaugeId/edit'
    | '/profiles/$profileId/edit'
    | '/projects/$projectId/edit'
    | '/projects/$projectId/knit'
    | '/projects/$projectId/log'
    | '/projects/$projectId/refs'
    | '/yarn/$yarnId/edit'
    | '/projects/$projectId/'
    | '/yarn/$yarnId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/inspiration'
    | '/settings'
    | '/share'
    | '/charts/$chartId'
    | '/charts/new'
    | '/gauge/calc'
    | '/gauge/new'
    | '/patterns/$patternId'
    | '/patterns/new'
    | '/profiles/new'
    | '/projects/new'
    | '/yarn/calc'
    | '/yarn/new'
    | '/charts'
    | '/gauge'
    | '/needles'
    | '/patterns'
    | '/profiles'
    | '/projects'
    | '/yarn'
    | '/gauge/$gaugeId/edit'
    | '/profiles/$profileId/edit'
    | '/projects/$projectId/edit'
    | '/projects/$projectId/knit'
    | '/projects/$projectId/log'
    | '/projects/$projectId/refs'
    | '/yarn/$yarnId/edit'
    | '/projects/$projectId'
    | '/yarn/$yarnId'
  id:
    | '__root__'
    | '/'
    | '/inspiration'
    | '/settings'
    | '/share'
    | '/charts/$chartId'
    | '/charts/new'
    | '/gauge/calc'
    | '/gauge/new'
    | '/patterns/$patternId'
    | '/patterns/new'
    | '/profiles/new'
    | '/projects/new'
    | '/yarn/calc'
    | '/yarn/new'
    | '/charts/'
    | '/gauge/'
    | '/needles/'
    | '/patterns/'
    | '/profiles/'
    | '/projects/'
    | '/yarn/'
    | '/gauge/$gaugeId/edit'
    | '/profiles/$profileId/edit'
    | '/projects/$projectId/edit'
    | '/projects/$projectId/knit'
    | '/projects/$projectId/log'
    | '/projects/$projectId/refs'
    | '/yarn/$yarnId/edit'
    | '/projects/$projectId/'
    | '/yarn/$yarnId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InspirationRoute: typeof InspirationRoute
  SettingsRoute: typeof SettingsRoute
  ShareRoute: typeof ShareRoute
  ChartsChartIdRoute: typeof ChartsChartIdRoute
  ChartsNewRoute: typeof ChartsNewRoute
  GaugeCalcRoute: typeof GaugeCalcRoute
  GaugeNewRoute: typeof GaugeNewRoute
  PatternsPatternIdRoute: typeof PatternsPatternIdRoute
  PatternsNewRoute: typeof PatternsNewRoute
  ProfilesNewRoute: typeof ProfilesNewRoute
  ProjectsNewRoute: typeof ProjectsNewRoute
  YarnCalcRoute: typeof YarnCalcRoute
  YarnNewRoute: typeof YarnNewRoute
  ChartsIndexRoute: typeof ChartsIndexRoute
  GaugeIndexRoute: typeof GaugeIndexRoute
  NeedlesIndexRoute: typeof NeedlesIndexRoute
  PatternsIndexRoute: typeof PatternsIndexRoute
  ProfilesIndexRoute: typeof ProfilesIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  YarnIndexRoute: typeof YarnIndexRoute
  GaugeGaugeIdEditRoute: typeof GaugeGaugeIdEditRoute
  ProfilesProfileIdEditRoute: typeof ProfilesProfileIdEditRoute
  ProjectsProjectIdEditRoute: typeof ProjectsProjectIdEditRoute
  ProjectsProjectIdKnitRoute: typeof ProjectsProjectIdKnitRoute
  ProjectsProjectIdLogRoute: typeof ProjectsProjectIdLogRoute
  ProjectsProjectIdRefsRoute: typeof ProjectsProjectIdRefsRoute
  YarnYarnIdEditRoute: typeof YarnYarnIdEditRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
  YarnYarnIdIndexRoute: typeof YarnYarnIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspiration': {
      id: '/inspiration'
      path: '/inspiration'
      fullPath: '/inspiration'
      preLoaderRoute: typeof InspirationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yarn/': {
      id: '/yarn/'
      path: '/yarn'
      fullPath: '/yarn/'
      preLoaderRoute: typeof YarnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles/': {
      id: '/profiles/'
      path: '/profiles'
      fullPath: '/profiles/'
      preLoaderRoute: typeof ProfilesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patterns/': {
      id: '/patterns/'
      path: '/patterns'
      fullPath: '/patterns/'
      preLoaderRoute: typeof PatternsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/needles/': {
      id: '/needles/'
      path: '/needles'
      fullPath: '/needles/'
      preLoaderRoute: typeof NeedlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gauge/': {
      id: '/gauge/'
      path: '/gauge'
      fullPath: '/gauge/'
      preLoaderRoute: typeof GaugeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charts/': {
      id: '/charts/'
      path: '/charts'
      fullPath: '/charts/'
      preLoaderRoute: typeof ChartsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yarn/new': {
      id: '/yarn/new'
      path: '/yarn/new'
      fullPath: '/yarn/new'
      preLoaderRoute: typeof YarnNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yarn/calc': {
      id: '/yarn/calc'
      path: '/yarn/calc'
      fullPath: '/yarn/calc'
      preLoaderRoute: typeof YarnCalcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles/new': {
      id: '/profiles/new'
      path: '/profiles/new'
      fullPath: '/profiles/new'
      preLoaderRoute: typeof ProfilesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patterns/new': {
      id: '/patterns/new'
      path: '/patterns/new'
      fullPath: '/patterns/new'
      preLoaderRoute: typeof PatternsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patterns/$patternId': {
      id: '/patterns/$patternId'
      path: '/patterns/$patternId'
      fullPath: '/patterns/$patternId'
      preLoaderRoute: typeof PatternsPatternIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gauge/new': {
      id: '/gauge/new'
      path: '/gauge/new'
      fullPath: '/gauge/new'
      preLoaderRoute: typeof GaugeNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gauge/calc': {
      id: '/gauge/calc'
      path: '/gauge/calc'
      fullPath: '/gauge/calc'
      preLoaderRoute: typeof GaugeCalcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charts/new': {
      id: '/charts/new'
      path: '/charts/new'
      fullPath: '/charts/new'
      preLoaderRoute: typeof ChartsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charts/$chartId': {
      id: '/charts/$chartId'
      path: '/charts/$chartId'
      fullPath: '/charts/$chartId'
      preLoaderRoute: typeof ChartsChartIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yarn/$yarnId/': {
      id: '/yarn/$yarnId/'
      path: '/yarn/$yarnId'
      fullPath: '/yarn/$yarnId/'
      preLoaderRoute: typeof YarnYarnIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yarn/$yarnId/edit': {
      id: '/yarn/$yarnId/edit'
      path: '/yarn/$yarnId/edit'
      fullPath: '/yarn/$yarnId/edit'
      preLoaderRoute: typeof YarnYarnIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/refs': {
      id: '/projects/$projectId/refs'
      path: '/projects/$projectId/refs'
      fullPath: '/projects/$projectId/refs'
      preLoaderRoute: typeof ProjectsProjectIdRefsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/log': {
      id: '/projects/$projectId/log'
      path: '/projects/$projectId/log'
      fullPath: '/projects/$projectId/log'
      preLoaderRoute: typeof ProjectsProjectIdLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/knit': {
      id: '/projects/$projectId/knit'
      path: '/projects/$projectId/knit'
      fullPath: '/projects/$projectId/knit'
      preLoaderRoute: typeof ProjectsProjectIdKnitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/edit': {
      id: '/projects/$projectId/edit'
      path: '/projects/$projectId/edit'
      fullPath: '/projects/$projectId/edit'
      preLoaderRoute: typeof ProjectsProjectIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles/$profileId/edit': {
      id: '/profiles/$profileId/edit'
      path: '/profiles/$profileId/edit'
      fullPath: '/profiles/$profileId/edit'
      preLoaderRoute: typeof ProfilesProfileIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gauge/$gaugeId/edit': {
      id: '/gauge/$gaugeId/edit'
      path: '/gauge/$gaugeId/edit'
      fullPath: '/gauge/$gaugeId/edit'
      preLoaderRoute: typeof GaugeGaugeIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InspirationRoute: InspirationRoute,
  SettingsRoute: SettingsRoute,
  ShareRoute: ShareRoute,
  ChartsChartIdRoute: ChartsChartIdRoute,
  ChartsNewRoute: ChartsNewRoute,
  GaugeCalcRoute: GaugeCalcRoute,
  GaugeNewRoute: GaugeNewRoute,
  PatternsPatternIdRoute: PatternsPatternIdRoute,
  PatternsNewRoute: PatternsNewRoute,
  ProfilesNewRoute: ProfilesNewRoute,
  ProjectsNewRoute: ProjectsNewRoute,
  YarnCalcRoute: YarnCalcRoute,
  YarnNewRoute: YarnNewRoute,
  ChartsIndexRoute: ChartsIndexRoute,
  GaugeIndexRoute: GaugeIndexRoute,
  NeedlesIndexRoute: NeedlesIndexRoute,
  PatternsIndexRoute: PatternsIndexRoute,
  ProfilesIndexRoute: ProfilesIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  YarnIndexRoute: YarnIndexRoute,
  GaugeGaugeIdEditRoute: GaugeGaugeIdEditRoute,
  ProfilesProfileIdEditRoute: ProfilesProfileIdEditRoute,
  ProjectsProjectIdEditRoute: ProjectsProjectIdEditRoute,
  ProjectsProjectIdKnitRoute: ProjectsProjectIdKnitRoute,
  ProjectsProjectIdLogRoute: ProjectsProjectIdLogRoute,
  ProjectsProjectIdRefsRoute: ProjectsProjectIdRefsRoute,
  YarnYarnIdEditRoute: YarnYarnIdEditRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
  YarnYarnIdIndexRoute: YarnYarnIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
