/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as YarnIndexRouteImport } from './routes/yarn.index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as GaugeIndexRouteImport } from './routes/gauge.index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const YarnIndexRoute = YarnIndexRouteImport.update({
  id: '/yarn/',
  path: '/yarn/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const GaugeIndexRoute = GaugeIndexRouteImport.update({
  id: '/gauge/',
  path: '/gauge/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/gauge/': typeof GaugeIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/yarn/': typeof YarnIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/gauge': typeof GaugeIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/yarn': typeof YarnIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/gauge/': typeof GaugeIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/yarn/': typeof YarnIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/settings' | '/gauge/' | '/projects/' | '/yarn/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/settings' | '/gauge' | '/projects' | '/yarn'
  id: '__root__' | '/' | '/settings' | '/gauge/' | '/projects/' | '/yarn/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  GaugeIndexRoute: typeof GaugeIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  YarnIndexRoute: typeof YarnIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yarn/': {
      id: '/yarn/'
      path: '/yarn'
      fullPath: '/yarn/'
      preLoaderRoute: typeof YarnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gauge/': {
      id: '/gauge/'
      path: '/gauge'
      fullPath: '/gauge/'
      preLoaderRoute: typeof GaugeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  GaugeIndexRoute: GaugeIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  YarnIndexRoute: YarnIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
